# Generated by Django 4.1 on 2023-12-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('article_number', models.IntegerField(blank=True, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_num', models.IntegerField(blank=True, max_length=2)),
                ('m_num', models.IntegerField(blank=True, max_length=1)),
                ('l_num', models.IntegerField(blank=True, max_length=1)),
                ('contained_items', models.ManyToManyField(blank=True, to='stockmanager.stockeditem')),
            ],
        ),
    ]
