# Generated by Django 4.1 on 2024-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_num', models.CharField(max_length=2)),
                ('m_num', models.CharField(default=0, max_length=1)),
                ('l_num', models.CharField(default=0, max_length=1)),
            ],
            options={
                'ordering': ['f_num', 'm_num', 'l_num'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('article_number', models.IntegerField(default=0)),
                ('locations', models.ManyToManyField(to='stockmanager.location')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
