# Generated by Django 4.1 on 2024-01-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockeditem',
            name='article_number',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
