# Generated by Django 4.1 on 2024-01-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article_number',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
