# Generated by Django 4.1 on 2024-01-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0002_alter_stockeditem_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='f_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='l_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='m_num',
            field=models.IntegerField(),
        ),
    ]
