# Generated by Django 4.1 on 2024-01-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0003_alter_location_f_num_alter_location_l_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='f_num',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='l_num',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='m_num',
            field=models.CharField(max_length=1),
        ),
    ]
