# Generated by Django 4.1 on 2024-01-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0004_alter_location_f_num_alter_location_l_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockeditem',
            name='article_number',
            field=models.IntegerField(blank=True),
        ),
    ]
