# Generated by Django 4.1 on 2024-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0005_alter_stockeditem_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockeditem',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
